### ISSUE TITLE
 'str' object has no attribute 'format'

### ISSUE THREAD

**Issue by ghost** [egonSchiele/Django-EditArea#1]
I can't implement it.

I copied files and when I try to open a page with the widget it gives:

TemplateSyntaxError
Caught AttributeError while rendering: 'str' object has no attribute 'format'
editarea.py in render, line 57

I am not sure if this is connected that I use not the field in a Model but widget in a Form, like so:

class TemplateForm(forms.Form):
    content = forms.CharField(
        widget= editarea.EditArea()
    )

because I want to use it to edit templates (with django-templatesadmin), that has no models at all.

**Comment by egonSchiele** [comment]
"format" was introduced in Python 3.0 and only backported to 2.6. I'm using the ol' reliable "%" now so that bug should be fixed.
